name: CI/CD Pipeline

on:
  push:
    branches:  [master]
jobs:
  build-test-deply:
    runs-on:  ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t imumesh/ci-cd-demo .

      - name: Push Docker image
        run: docker push imumesh/ci-cd-demo
