name: CI/CD Pipeline

on:
  push:
    branches:  [master]
    tags:
      - 'v*.*.*'
jobs:
  build-test-deply:
    runs-on:  ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Get Git tag or use 'latest'
        id: vars
        run: |
          echo "GIT_TAG=${GITHUB_REF##*/}" >> GITHUB_ENV
          echo "VERSION_TAG=${GITHUB_REF_TYPE == 'tag' && GIT_REF_NAME || 'latest'}"

      - name: Build Docker image
        run: |
          docker build -t ${{secrets.DOCKER_USERNAME}}/ci-cd-demo:latest .
          docker tag  ${{secrets.DOCKER_USERNAME}}/ci-cd-demo:latest ${{ secrets.DOCKER_USERNAME }}/ci-cd-demo:{GIT_TAG}


      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/ci-cd-demo:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/ci-cd-demo:${GIT_TAG}

  release:
    name: GitHub Release
    if: startWith(github.ref, 'refs/tags/v')
    needs: build-test-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
